In [1]:
import tensorflow as tf
import cv2
image_file = "dog_3184.jpg"
image_raw = tf.gfile.FastGFile(image_file,'rb').read()

/home/luql/anaconda2/envs/py3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [ ]:
image = tf.image.decode_jpeg(image_raw)

In [ ]:
with tf.Session() as sess:
    print(image.eval())
    cv2.imshow("image", image.eval())
    cv2.waitKey(0)
    cv2.destroyAllWindows()

[[[146 153 159]
  [146 153 159]
  [146 153 159]
  ..., 
  [197 192 188]
  [197 192 188]
  [197 192 188]]

 [[145 152 158]
  [145 152 158]
  [145 152 158]
  ..., 
  [202 197 193]
  [202 197 193]
  [202 197 193]]

 [[145 152 158]
  [145 152 158]
  [145 152 158]
  ..., 
  [205 200 196]
  [205 200 196]
  [205 200 196]]

 ..., 
 [[ 70  62  59]
  [ 79  71  68]
  [ 73  65  62]
  ..., 
  [ 93  88  85]
  [ 94  89  86]
  [ 94  89  86]]

 [[ 68  60  57]
  [ 75  67  64]
  [ 69  61  58]
  ..., 
  [ 79  74  71]
  [ 78  73  70]
  [ 75  70  67]]

 [[ 71  63  60]
  [ 74  66  63]
  [ 67  59  56]
  ..., 
  [ 59  53  53]
  [ 51  45  45]
  [ 42  36  36]]]
